### PR TITLE
Add tests

### PR DESCRIPTION
**Pull request by mruwnik**
I added tests - run with 'py.test -v'

### CODE REVIEW

**Comment by lad1337** [comment]
have a look at #3

**Comment by chriscanal** [comment]
You guys should close this

**Comment by lad1337** [comment]
@chriscanal why the interest in this super old repo? based on your comment i archived it then realising you just ment the MR ... does this still work? do you want to use it? otherwise i would archive this repo

**Comment by chriscanal** [comment]
I work with Daniel ([mruwnik](https://github.com/mruwnik)) and he's recently opened a ton of PRs and I'm trying to review all of them. lol. This one came up and I was thinking, that I might as well ask for it to be closed so it doesn't keep coming up

**Pull request closed without merging**
