### PR TITLE
Updated xml tag definitions

### PR DESCRIPTION
**Pull request by mruwnik**
It appears that anidb changed how they represent tags, which meant that Anime.load() would raise an exception.

### CODE REVIEW

**Comment by lad1337** [comment]
Thanks looks awesome ... Didn't think someone was using it ^^

**Comment by mruwnik** [comment]
it's needed for the aniDB plugin of XDM to work

**Comment by lad1337** [comment]
Wow you are actually using XDM ?
FYI I'm rewriting it completely

**Comment by mruwnik** [comment]
I don't know yet. So far it appears to do what I want, or at least in such a way that makes it easy to get it do so. Although I've only just started trying it out. Need any help with the rewrite?

**Comment by lad1337** [comment]
about the help on the rewrite have a look at https://github.com/lad1337/XDM/pull/197
its very basic so far with mainly the structure in place

**Pull request merged**
